# Generated by Django 4.0.1 on 2022-01-20 16:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='average_raging',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.PositiveSmallIntegerField(default=1000, validators=[django.core.validators.MaxValueValidator(2020), django.core.validators.MinValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='book',
            name='ratings_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
