# Generated by Django 4.0.1 on 2022-01-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
