# Generated by Django 4.0.1 on 2022-01-20 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0002_alter_book_average_raging_alter_book_published_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='average_raging',
            new_name='average_rating',
        ),
    ]
