# Generated by Django 4.0.1 on 2022-01-28 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0003_alter_bookauthor_author_alter_bookauthor_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookauthor',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_api.author'),
        ),
        migrations.AlterField(
            model_name='bookauthor',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_api.book'),
        ),
        migrations.AlterField(
            model_name='bookcategory',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_api.book'),
        ),
        migrations.AlterField(
            model_name='bookcategory',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_api.category'),
        ),
    ]
