# Generated by Django 4.0.1 on 2022-01-29 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0004_alter_bookauthor_author_alter_bookauthor_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookauthor',
            name='name',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='bookcategory',
            name='name',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='bookauthor',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_api.author'),
        ),
        migrations.AlterField(
            model_name='bookauthor',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_api.book'),
        ),
        migrations.AlterField(
            model_name='bookcategory',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_api.book'),
        ),
        migrations.AlterField(
            model_name='bookcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_api.category'),
        ),
    ]
